seed: 42

agent:
  name: TD3
  memory_size: 100000
  learning_rate: 1.0e-4
  batch_size: 128
  gradient_steps: 1
  actor_learning_rate: 1.0e-4
  critic_learning_rate: 1.0e-4
  discount_factor: 0.99
  polyak: 0.01
  policy_delay: 2
  smooth_regularization_clip: 0.25
  exploration:
    noise_type: gaussian
    initial_scale: 0.5
    final_scale: 0.05
    timesteps: 50000
  random_timesteps: 0
  learning_starts: 1000
  clip_actions_min: -1.0
  clip_actions_max: 1.0
  rewards_shaper: null
  state_preprocessor: null
  state_preprocessor_kwargs: {}
  grad_norm_clip: 1.0
  experiment:
    write_interval: 100

trainer:
  timesteps: 50000                 # 50k timesteps - fast benchmarking
  parallel_seeds: 1                # Number of parallel training runs
